### ISSUE TITLE
First it's cool ,second i have some questions.

### ISSUE THREAD

**Issue by FRANDAVID** [maxant/rules#2]
hi,Ant
When I found this tool, I think it is so cool, now i have some questions。In particular, I hope you can help me。my use case is :
1. i have many rules and user's action list in db or redis,   The rules like this  , 
   A:a person who register 3 days ago ,and Continuous login 10 days，and browse Electronic products 10 times。
   B:a person who browse Electronic products 10 times and browse Women's clothing products 5 times，
   now when a new user action(like david login  2016-05-20 08:00:00) come , i wana to know this action whether match rule A ,use david's action  list history  in redis. can "maxant/rules" do that ?
2. if "maxant/rules" can do that now ,it is there anywway to transform the naturally lanaguage,to mvel expression.or is there anyway in web application to save the mvel expression to DB.

a person who register 3 days ago ,and Continuous login 10 days，and browse Electronic products 10 times=====>register >3 && login >10 && browse 01001
e.g:01001 means products Id in DB

Thank you so much!!! :

**Comment by maxant** [comment]
Hi, sorry I only just saw this issue.

1) Yes - see https://github.com/maxant/rules/blob/master/rules-java8/src/test/java/ch/maxant/rules/blackbox/Issue2Test.java

2) This library does not directly contain code for saving rules to a database because there are just too many options available. But you could easily write some code to do that, since the Rule class has only string and integer attributes.  I have however done exactly what you said in a private project. 

As for converting natural language to mvel expressions... I don't think it is that hard to get for example business analysts to understand mvel. In the test I referenced above, I showed that you can used mvel keywords like "and" and "or" rather than the normal && and ||.  Otherwise you could imagine writing a nice web UI which allows the user to drag and drop certain predefined blocks to make up rules. The web app would then convert that into valid mvel expressions.
